-- توليد تلقائي من scripts/json-to-sql.js
-- شغّل هذا الملف في Supabase SQL Editor بعد schema.sql

BEGIN;

DELETE FROM products WHERE TRUE;

INSERT INTO products
  (name, name_en, description, description_en, price, image_url, category, family, color_key, color_hex, color_name, color_name_en, cat_group, sort_order, is_active)
VALUES
  ('جوز سراير وردي', 'Pink Bed Pair', 'جوز سراير حديد بلون وردي أنيق، مزخرف بنقوش ذهبية فنية على مسند الرأس والقدم. تصميم كلاسيكي فاخر يجمع بين المتانة والجمال، مع شبكة معدنية قوية وكرات زخرفية ذهبية على الأطراف. مناسب لغرف النوم الكلاسيكية.', 'Elegant pink wrought iron bed pair with artistic gold scrollwork on headboard and footboard. A luxurious classic design combining durability and beauty, featuring a strong metal mesh base and decorative gold finials. Perfect for classic bedrooms.', 410000, 'images/jawz-sarir.png', 'store', NULL, NULL, NULL, NULL, NULL, NULL, 66, TRUE),
  ('حاملة زير', 'Zir Stand', 'حاملة زير حديدية متينة ومتقنة الصنع، مصممة خصيصاً لحمل الزير (الجرة الفخارية) بأمان واستقرار. تصميم عملي وأنيق يضمن ثبات الزير ويمنع انقلابه، مع تفاصيل معدنية محكمة تعكس جودة الصناعة اليدوية. مناسبة للمنازل والحدائق والمزارع.', 'Sturdy and well-crafted wrought iron Zir stand, designed specifically to hold the traditional clay water cooler safely and securely. A practical and elegant design ensures stability and prevents tipping, with precise metal details reflecting quality handcraftsmanship. Suitable for homes, gardens, and farms.', 70000, 'images/jawz-sarir-3.jpg', 'store', NULL, NULL, NULL, NULL, NULL, NULL, 65, TRUE),
  ('جوز سراير زهري مزخرف', 'Ornate Pink Bed Pair', 'جوز سراير حديد بلون زهري فاتح مع زخارف ذهبية بارزة، مزين بنقوش نباتية ورموز دائرية على مسند الرأس والقدم. التصميم الفاخر يجمع بين الأناقة الكلاسيكية والمتانة الحديدية، مع كرات معدنية ذهبية على الأطراف تضفي لمسة ملكية.', 'Light pink wrought iron bed pair with prominent gold decorative scrollwork, featuring botanical patterns and circular medallions on headboard and footboard. The luxurious design blends classical elegance with iron durability, with gold metallic finials adding a royal touch.', 410000, 'images/jawz-sarir-1.jpg', 'store', NULL, NULL, NULL, NULL, NULL, NULL, 64, TRUE),
  ('جوز سراير خام', 'Raw Iron Bed Pair', 'جوز سراير حديدية خام غير مطلية، مصنوعة من حديد قوي بمظهر صناعي أصيل. تصميم بسيط وعملي يركز على المتانة والقوة، مناسب للذين يفضلون طلاء السرير باللون الذي يختارونه بأنفسهم. الهيكل المعدني الصلب يضمن عمراً طويلاً.', 'Unfinished raw iron bed pair, crafted from strong iron with an authentic industrial look. A simple and practical design focused on durability and strength, ideal for those who prefer to paint the bed in their chosen color. The solid metal frame ensures long life.', 410000, 'images/jawz-sarir-2.jpg', 'store', NULL, NULL, NULL, NULL, NULL, NULL, 63, TRUE),
  ('جوز سراير بني داكن', 'Dark Brown Bed Pair', 'جوز سراير حديد بلون بني داكن برونزي، مزخرف بنقوش يدوية فنية على مسند الرأس والقدم. تصميم كلاسيكي أنيق يجمع بين الفخامة والمتانة، مع شبكة معدنية قوية ومسند رأس مزخرف بتفاصيل نباتية دقيقة. مناسب لغرف النوم التقليدية.', 'Dark bronze-brown wrought iron bed pair with handcrafted artistic scrollwork on headboard and footboard. An elegant classic design combining luxury and durability, with a strong metal mesh base and finely detailed botanical headboard. Perfect for traditional bedrooms.', 410000, 'images/hamilat-zeer.png', 'store', NULL, NULL, NULL, NULL, NULL, NULL, 62, TRUE),
  ('جوز سراير أسود مزخرف', 'Ornate Black Bed Pair', 'جوز سراير حديد أسود مزخرف بنقوش ذهبية وشرقية فاخرة، مزين بزخارف نباتية ورموز إسلامية على مسند الرأس والقدم. اللون الأسود اللامع مع التفاصيل الذهبية يضفي فخامة استثنائية على غرفة النوم. الحديد المعالج ضد الصدأ يضمن المتانة.', 'Black wrought iron bed pair with luxurious gold and Eastern ornamental scrollwork, decorated with botanical patterns and Islamic motifs on headboard and footboard. The glossy black with gold details adds exceptional elegance to the bedroom. Anti-rust treated iron ensures durability.', 410000, 'images/jawz-sarir-4.jpg', 'store', NULL, NULL, NULL, NULL, NULL, NULL, 61, TRUE),
  ('شرفة حديد - أسود', 'Iron Balcony - Black', 'شرفة حديد بلون أسود كلاسيكي، مزخرفة بنقوش فنية على الدرابزين. تصميم متين وآمن يمنح الشرفة مظهراً أنيقاً. مناسبة للمنازل والشقق.', 'Classic black wrought iron balcony with artistic patterns on the railing. A sturdy and safe design giving the balcony an elegant appearance. Suitable for homes and apartments.', NULL, 'images/orders/balcony.png', 'orders', 'balcony', 'black', '#1a1a1a', 'أسود', 'Black', 'outdoor', 60, TRUE),
  ('شرفة حديد - رمادي', 'Iron Balcony - Grey', 'شرفة حديد بلون رمادي عصري، مزخرفة بتصميم أنيق. اللون الرمادي يناسب الواجهات المعاصرة والتصاميم الحديثة. مناسبة للمباني الحديثة.', 'Modern grey wrought iron balcony with an elegant design. The grey color suits contemporary facades and modern designs. Suitable for modern buildings.', NULL, 'images/orders/balcony.png', 'orders', 'balcony', 'grey', '#808080', 'رمادي', 'Grey', 'outdoor', 59, TRUE),
  ('شرفة حديد - أبيض', 'Iron Balcony - White', 'شرفة حديد بلون أبيض نقي، مزخرفة بنقوش رقيقة. اللون الأبيض يمنح الشرفة إحساساً بالنظافة والرقي. مثالية للواجهات ذات الديكور الفاتح.', 'Pure white wrought iron balcony with delicate patterns. The white color gives the balcony a sense of cleanliness and elegance. Ideal for light-decor facades.', NULL, 'images/orders/balcony.png', 'orders', 'balcony', 'white', '#f0f0f0', 'أبيض', 'White', 'outdoor', 58, TRUE),
  ('سرير بطابقين - أسود', 'Bunk Iron Bed - Black', 'سرير حديد بطابقين بلون أسود متين، مصمم لتحمل الاستخدام المكثف. مثالي لغرف الأطفال والشباب أو المساحات المشتركة. سلم حديدي آمن ومريح مع حماية جوانبية للطابق العلوي.', 'Sturdy black wrought iron bunk bed, designed for heavy use. Ideal for children''s rooms, youth rooms, or shared spaces. Safe and comfortable iron ladder with upper bunk side protection.', NULL, 'images/orders/bed-bunk.png', 'orders', 'bed-bunk', 'black', '#1a1a1a', 'أسود', 'Black', 'beds', 57, TRUE),
  ('سرير بطابقين - رمادي', 'Bunk Iron Bed - Grey', 'سرير حديد بطابقين بلون رمادي عصري، تصميم أنيق ومتين في آن واحد. اللون الرمادي يناسب مختلف الديكورات ويعطي مظهراً حديثاً. مثالي لغرف الأطفال المشتركة.', 'Modern grey wrought iron bunk bed, combining elegant design with sturdy construction. The grey color suits various decors and gives a contemporary look. Ideal for shared children''s rooms.', NULL, 'images/orders/bed-bunk.png', 'orders', 'bed-bunk', 'grey', '#808080', 'رمادي', 'Grey', 'beds', 56, TRUE),
  ('سرير بطابقين - أبيض', 'Bunk Iron Bed - White', 'سرير حديد بطابقين بلون أبيض مشرق، يمنح الغرفة إحساساً بالنظافة والاتساع. تصميم عملي وأنيق مع حماية جوانبية كاملة. مناسب لغرف الأطفال ذات المساحات المحدودة.', 'Bright white wrought iron bunk bed, giving the room a sense of cleanliness and spaciousness. Practical and elegant design with full side protection. Suitable for limited-space children''s rooms.', NULL, 'images/orders/bed-bunk.png', 'orders', 'bed-bunk', 'white', '#f0f0f0', 'أبيض', 'White', 'beds', 55, TRUE),
  ('سرير كلاسيكي - أسود', 'Classic Iron Bed - Black', 'سرير حديد كلاسيكي بلون أسود أنيق، مزخرف بنقوش يدوية فنية على مسند الرأس والقدم. تصميم تقليدي عريق يجمع بين الفخامة والمتانة، مناسب لغرف النوم الكلاسيكية. الحديد المعالج ضد الصدأ يضمن عمراً طويلاً.', 'Classic black wrought iron bed with handcrafted artistic scrollwork on the headboard and footboard. A timeless traditional design combining luxury and durability, perfect for classic bedrooms. Treated anti-rust iron ensures long life.', NULL, 'images/orders/bed-classic.png', 'orders', 'bed-classic', 'black', '#1a1a1a', 'أسود', 'Black', 'beds', 54, TRUE),
  ('سرير كلاسيكي - ذهبي', 'Classic Iron Bed - Gold', 'سرير حديد كلاسيكي بلمسات ذهبية فاخرة، مزخرف بنقوش يدوية على مسند الرأس والقدم. اللون الذهبي يضفي فخامة وبريقاً على غرفة النوم. تصميم يجمع بين الأصالة والرونق الملكي.', 'Classic wrought iron bed with luxurious gold accents, handcrafted scrollwork on headboard and footboard. The gold finish adds elegance and brilliance to your bedroom. A design blending authenticity with royal charm.', NULL, 'images/orders/bed-classic.png', 'orders', 'bed-classic', 'gold', '#D4A017', 'ذهبي', 'Gold', 'beds', 53, TRUE),
  ('سرير كلاسيكي - أبيض', 'Classic Iron Bed - White', 'سرير حديد كلاسيكي بلون أبيض نقي، مزخرف بنقوش يدوية رقيقة. اللون الأبيض يمنح غرفة النوم إحساساً بالنظافة والهدوء والاتساع. مثالي للغرف ذات الديكور الفاتح.', 'Classic white wrought iron bed with delicate handcrafted patterns. The white color gives the bedroom a sense of cleanliness, tranquility, and spaciousness. Ideal for light-colored decor rooms.', NULL, 'images/orders/bed-classic.png', 'orders', 'bed-classic', 'white', '#f0f0f0', 'أبيض', 'White', 'beds', 52, TRUE),
  ('سرير ملكي - أسود وذهبي', 'Royal Iron Bed - Black & Gold', 'سرير حديد ملكي فاخر باللون الأسود مع زخارف ذهبية، تصميم تاجي فخم على مسند الرأس يمنح غرفة النوم طابعاً ملكياً. مصنوع من أجود أنواع الحديد المطاوع مع تشطيب مزدوج اللون.', 'Luxurious royal wrought iron bed in black with gold accents, featuring a crown-style headboard that gives the bedroom a regal character. Made from premium wrought iron with dual-color finish.', NULL, 'images/orders/bed-royal.png', 'orders', 'bed-royal', 'black-gold', '#2a2a2a', 'أسود وذهبي', 'Black & Gold', 'beds', 51, TRUE),
  ('سرير ملكي - نحاسي', 'Royal Iron Bed - Copper', 'سرير حديد ملكي بلون نحاسي دافئ، تصميم تاجي فخم مع زخارف نحاسية لامعة. اللون النحاسي يضفي دفئاً وأناقة كلاسيكية على المساحة. مناسب للديكورات الكلاسيكية والعتيقة.', 'Royal wrought iron bed in warm copper tone, with a crown-style design and shiny copper accents. The copper color adds warmth and classic elegance to the space. Suitable for classic and vintage decor.', NULL, 'images/orders/bed-royal.png', 'orders', 'bed-royal', 'copper', '#B87333', 'نحاسي', 'Copper', 'beds', 50, TRUE),
  ('سرير ملكي - فضي', 'Royal Iron Bed - Silver', 'سرير حديد ملكي بلون فضي لامع، تصميم تاجي فخم مع زخارف فضية راقية. اللون الفضي يمنح غرفة النوم إحساساً عصرياً وأنيقاً. مثالي للديكورات الحديثة والكلاسيكية على حد سواء.', 'Royal wrought iron bed in shiny silver, with a crown-style design and elegant silver accents. The silver color gives the bedroom a modern and sophisticated feel. Ideal for both contemporary and classic decor.', NULL, 'images/orders/bed-royal.png', 'orders', 'bed-royal', 'silver', '#C0C0C0', 'فضي', 'Silver', 'beds', 49, TRUE),
  ('أريكة حديد - أسود', 'Iron Bench - Black', 'أريكة حديد أنيقة بلون أسود، مزخرفة بنقوش فنية على الذراعين والظهر. مثالية للحدائق والشرفات والمتنزهات. مقعد مريح يتسع لشخصين مع مسند ذراعين مزخرف.', 'Elegant black wrought iron bench with artistic patterns on armrests and backrest. Ideal for gardens, balconies, and parks. Comfortable two-seat bench with decorated armrests.', NULL, 'images/orders/bench.png', 'orders', 'bench', 'black', '#1a1a1a', 'أسود', 'Black', 'chairs', 48, TRUE),
  ('أريكة حديد - بني', 'Iron Bench - Brown', 'أريكة حديد بلون بني دافئ، مزخرفة بنقوش فنية. اللون البني يتناغم مع الطبيعة والحدائق. مثالية للاستخدام الخارجي والداخلي بتصميم كلاسيكي دافئ.', 'Wrought iron bench in warm brown with artistic patterns. The brown color harmonizes with nature and gardens. Ideal for both outdoor and indoor use with a warm classic design.', NULL, 'images/orders/bench.png', 'orders', 'bench', 'brown', '#8B4513', 'بني', 'Brown', 'chairs', 47, TRUE),
  ('أريكة حديد - أخضر', 'Iron Bench - Green', 'أريكة حديد بلون أخضر طبيعي، مزخرفة بنقوش فنية على الذراعين والظهر. اللون الأخضر يندمج مع الطبيعة ويمنح الحديقة جمالاً إضافياً. مثالية للمتنزهات والحدائق العامة.', 'Wrought iron bench in natural green with artistic patterns on armrests and backrest. The green color blends with nature and adds beauty to the garden. Ideal for parks and public gardens.', NULL, 'images/orders/bench.png', 'orders', 'bench', 'green', '#2E8B57', 'أخضر', 'Green', 'chairs', 46, TRUE),
  ('رف كتب حديد - أسود', 'Iron Bookshelf - Black', 'رف كتب حديدي بلون أسود، تصميم متين مع رفوف متعددة وجوانب مزخرفة. مثالي للمكتبات وغرف المعيشة. يتسع لعدد كبير من الكتب والمجلات والتحف.', 'Black iron bookshelf with a sturdy design, multiple shelves, and decorated sides. Ideal for libraries and living rooms. Accommodates a large number of books, magazines, and collectibles.', NULL, 'images/orders/bookshelf.png', 'orders', 'bookshelf', 'black', '#1a1a1a', 'أسود', 'Black', 'storage', 45, TRUE),
  ('رف كتب حديد - أحمر', 'Iron Bookshelf - Red', 'رف كتب حديدي بلون أحمر جريء، تصميم ملفت يجعله قطعة ديكور مميزة. اللون الأحمر يضفي حيوية وحماساً على المكان. مثالي للمكاتب الإبداعية وغرف الأطفال.', 'Bold red iron bookshelf with a striking design that makes it a distinctive decor piece. The red color adds vitality and enthusiasm to the space. Ideal for creative offices and children''s rooms.', NULL, 'images/orders/bookshelf.png', 'orders', 'bookshelf', 'red', '#cc0000', 'أحمر', 'Red', 'storage', 44, TRUE),
  ('رف كتب حديد - أبيض', 'Iron Bookshelf - White', 'رف كتب حديدي بلون أبيض مشرق، تصميم أنيق وعصري. اللون الأبيض يمنح المكتبة مظهراً نظيفاً ومرتباً. مناسب للمكاتب والغرف ذات الديكور الفاتح.', 'Bright white iron bookshelf with an elegant and modern design. The white color gives the library a clean and organized appearance. Suitable for offices and light-decor rooms.', NULL, 'images/orders/bookshelf.png', 'orders', 'bookshelf', 'white', '#f0f0f0', 'أبيض', 'White', 'storage', 43, TRUE),
  ('كرسي كلاسيكي - أسود', 'Classic Iron Chair - Black', 'كرسي حديد كلاسيكي بلون أسود أنيق، مزخرف بنقوش يدوية فنية على الظهر والذراعين. تصميم كلاسيكي عريق يناسب الحدائق والمطاعم والمنازل. مقعد مريح ومتين.', 'Classic black wrought iron chair with handcrafted artistic patterns on the backrest and armrests. A timeless classic design suitable for gardens, restaurants, and homes. Comfortable and sturdy seat.', NULL, 'images/orders/chair-classic.png', 'orders', 'chair-classic', 'black', '#1a1a1a', 'أسود', 'Black', 'chairs', 42, TRUE),
  ('كرسي كلاسيكي - برونزي', 'Classic Iron Chair - Bronze', 'كرسي حديد كلاسيكي بلون برونزي دافئ، مزخرف بنقوش يدوية على الظهر والذراعين. اللون البرونزي يضفي طابعاً عتيقاً وفاخراً. مناسب للديكورات الكلاسيكية والريفية.', 'Classic wrought iron chair in warm bronze, with handcrafted patterns on backrest and armrests. The bronze color adds a vintage and luxurious touch. Suitable for classic and rustic decor.', NULL, 'images/orders/chair-classic.png', 'orders', 'chair-classic', 'bronze', '#CD7F32', 'برونزي', 'Bronze', 'chairs', 41, TRUE),
  ('كرسي كلاسيكي - أبيض', 'Classic Iron Chair - White', 'كرسي حديد كلاسيكي بلون أبيض نقي، مزخرف بنقوش يدوية رقيقة. اللون الأبيض يمنح إحساساً بالنظافة والرقي. مثالي للحدائق والشرفات ذات الديكور الفاتح.', 'Classic white wrought iron chair with delicate handcrafted patterns. The white color gives a sense of cleanliness and elegance. Ideal for gardens and balconies with light decor.', NULL, 'images/orders/chair-classic.png', 'orders', 'chair-classic', 'white', '#f0f0f0', 'أبيض', 'White', 'chairs', 40, TRUE),
  ('كرسي عصري - أسود', 'Modern Iron Chair - Black', 'كرسي حديد عصري بتصميم بسيط وأنيق بلون أسود. خطوط نظيفة ومظهر حداثي يناسب الديكورات المعاصرة. خفيف الوزن ومتين في البناء، مثالي للمكاتب والمنازل العصرية.', 'Modern wrought iron chair with a sleek black design. Clean lines and contemporary appearance suitable for modern decor. Lightweight yet sturdy, ideal for offices and modern homes.', NULL, 'images/orders/chair-modern.png', 'orders', 'chair-modern', 'black', '#1a1a1a', 'أسود', 'Black', 'chairs', 39, TRUE),
  ('كرسي عصري - أزرق', 'Modern Iron Chair - Blue', 'كرسي حديد عصري بلون أزرق هادئ، تصميم أنيق يجمع بين البساطة والجمال. اللون الأزرق يمنح المكان هدوءاً وانتعاشاً. مناسب للحدائق والمساحات الخارجية.', 'Modern wrought iron chair in calm blue, an elegant design combining simplicity and beauty. The blue color gives the space tranquility and freshness. Suitable for gardens and outdoor areas.', NULL, 'images/orders/chair-modern.png', 'orders', 'chair-modern', 'blue', '#3366cc', 'أزرق', 'Blue', 'chairs', 38, TRUE),
  ('كرسي عصري - أحمر', 'Modern Iron Chair - Red', 'كرسي حديد عصري بلون أحمر جريء، تصميم عصري ملفت يضفي حيوية على المكان. مثالي للمقاهي والمطاعم ذات الطابع الحديث. اللون الأحمر يجعله قطعة ديكور مميزة.', 'Modern wrought iron chair in bold red, a striking contemporary design that adds vitality to any space. Ideal for modern cafes and restaurants. The red color makes it a distinctive decor piece.', NULL, 'images/orders/chair-modern.png', 'orders', 'chair-modern', 'red', '#cc0000', 'أحمر', 'Red', 'chairs', 37, TRUE),
  ('طاولة مكتب حديد - أسود', 'Iron Desk - Black', 'طاولة مكتب حديدية بلون أسود، تصميم صناعي عصري بخطوط بسيطة وقوية. مثالية للمكاتب وغرف العمل. هيكل متين مع سطح واسع ومساحة تخزين.', 'Black iron desk with a modern industrial design featuring simple, strong lines. Ideal for offices and workspaces. Sturdy frame with wide surface and storage space.', NULL, 'images/orders/desk.png', 'orders', 'desk', 'black', '#1a1a1a', 'أسود', 'Black', 'tables', 36, TRUE),
  ('طاولة مكتب حديد - رمادي', 'Iron Desk - Grey', 'طاولة مكتب حديدية بلون رمادي عصري، تصميم أنيق ومهني. اللون الرمادي يناسب بيئات العمل المعاصرة. مثالية للمكاتب والاستوديوهات.', 'Modern grey iron desk with an elegant and professional design. The grey color suits contemporary work environments. Ideal for offices and studios.', NULL, 'images/orders/desk.png', 'orders', 'desk', 'grey', '#808080', 'رمادي', 'Grey', 'tables', 35, TRUE),
  ('طاولة مكتب حديد - أبيض', 'Iron Desk - White', 'طاولة مكتب حديدية بلون أبيض نظيف، تصميم بسيط وأنيق. اللون الأبيض يمنح المكتب مظهراً مرتباً ومهنيّاً. مناسبة للمكاتب المنزلية.', 'Clean white iron desk with a simple and elegant design. The white color gives the office an organized and professional appearance. Suitable for home offices.', NULL, 'images/orders/desk.png', 'orders', 'desk', 'white', '#f0f0f0', 'أبيض', 'White', 'tables', 34, TRUE),
  ('باب حديد - أسود', 'Iron Door - Black', 'باب حديد متين بلون أسود، مزخرف بنقوش فنية وأشكال هندسية. تصميم أمن وجمالي في آن واحد. مقاوم للصدأ والتآكل مع إمكانية إضافة قفل أمني.', 'Sturdy black wrought iron door with artistic patterns and geometric shapes. A design combining security and beauty. Rust and corrosion resistant with option for security lock.', NULL, 'images/orders/door.png', 'orders', 'door', 'black', '#1a1a1a', 'أسود', 'Black', 'gates-doors', 33, TRUE),
  ('باب حديد - برونزي', 'Iron Door - Bronze', 'باب حديد بلون برونزي أنيق، مزخرف بنقوش فنية بلمسات برونزية. اللون البرونزي يمنح الباب طابعاً كلاسيكياً وراقياً. مناسب للمنازل والمكاتب الفاخرة.', 'Elegant bronze wrought iron door with artistic patterns and bronze accents. The bronze color gives the door a classic and refined character. Suitable for luxury homes and offices.', NULL, 'images/orders/door.png', 'orders', 'door', 'bronze', '#CD7F32', 'برونزي', 'Bronze', 'gates-doors', 32, TRUE),
  ('باب حديد - أبيض', 'Iron Door - White', 'باب حديد بلون أبيض مشرق، مزخرف بنقوش رقيقة وأنيقة. اللون الأبيض يمنح المدخل مظهراً نظيفاً ومرحباً. مناسب للمنازل ذات الديكور الفاتح.', 'Bright white wrought iron door with delicate and elegant patterns. The white color gives the entrance a clean and welcoming appearance. Suitable for light-decor homes.', NULL, 'images/orders/door.png', 'orders', 'door', 'white', '#f0f0f0', 'أبيض', 'White', 'gates-doors', 31, TRUE),
  ('بوابة حديد - أسود', 'Iron Gate - Black', 'بوابة حديد ضخمة بلون أسود، مزخرفة بنقوش فنية مميزة ولفائف حديدية. تصميم فخم يمنح المدخل طابعاً مهيباً. مناسبة للفيلات والقصور والمنشآت الكبرى.', 'Grand black wrought iron gate with distinctive artistic patterns and iron scrollwork. A luxurious design that gives the entrance a majestic character. Suitable for villas, palaces, and large establishments.', NULL, 'images/orders/gate.png', 'orders', 'gate', 'black', '#1a1a1a', 'أسود', 'Black', 'gates-doors', 30, TRUE),
  ('بوابة حديد - نحاسي', 'Iron Gate - Copper', 'بوابة حديد بلون نحاسي دافئ، مزخرفة بنقوش فنية بلمسات نحاسية. اللون النحاسي يضفي طابعاً كلاسيكياً وأنيقاً على المدخل. مناسبة للمنازل والحدائق.', 'Wrought iron gate in warm copper with artistic patterns and copper accents. The copper color adds a classic and elegant touch to the entrance. Suitable for homes and gardens.', NULL, 'images/orders/gate.png', 'orders', 'gate', 'copper', '#B87333', 'نحاسي', 'Copper', 'gates-doors', 29, TRUE),
  ('بوابة حديد - ذهبي', 'Iron Gate - Gold', 'بوابة حديد فاخرة بلون ذهبي، مزخرفة بنقوش ملكية ولمسات ذهبية لامعة. تمنح المدخل طابعاً ملكياً وأنيقاً. مثالية للقاعات والمنشآت الفاخرة.', 'Luxurious gold wrought iron gate with royal patterns and shiny gold accents. Gives the entrance a regal and elegant character. Ideal for halls and luxury establishments.', NULL, 'images/orders/gate.png', 'orders', 'gate', 'gold', '#D4A017', 'ذهبي', 'Gold', 'gates-doors', 28, TRUE),
  ('مرآة بإطار حديد - أسود', 'Iron Mirror Frame - Black', 'مرآة مزخرفة بإطار حديد بلون أسود، نقوش يدوية فنية على الإطار. تصميم أنيق يضفي لمسة فنية على الجدار. مناسبة لغرف المعيشة والمداخل.', 'Ornate mirror with a black wrought iron frame featuring handcrafted artistic patterns. An elegant design adding an artistic touch to the wall. Suitable for living rooms and entrances.', NULL, 'images/orders/mirror.png', 'orders', 'mirror', 'black', '#1a1a1a', 'أسود', 'Black', 'decor', 27, TRUE),
  ('مرآة بإطار حديد - ذهبي', 'Iron Mirror Frame - Gold', 'مرآة مزخرفة بإطار حديد بلون ذهبي فاخر، نقوش ملكية على الإطار. اللون الذهبي يضفي فخامة وبريقاً على المكان. مثالية للقاعات وغرف الاستقبال.', 'Ornate mirror with a luxurious gold wrought iron frame featuring royal patterns. The gold color adds luxury and brilliance to the space. Ideal for halls and reception rooms.', NULL, 'images/orders/mirror.png', 'orders', 'mirror', 'gold', '#D4A017', 'ذهبي', 'Gold', 'decor', 26, TRUE),
  ('مرآة بإطار حديد - فضي', 'Iron Mirror Frame - Silver', 'مرآة مزخرفة بإطار حديد بلون فضي لامع، نقوش أنيقة على الإطار. اللون الفضي يمنح المكان مظهراً عصرياً وراقياً. مناسبة للحمامات وغرف الملابس.', 'Ornate mirror with a shiny silver wrought iron frame featuring elegant patterns. The silver color gives the space a modern and refined look. Suitable for bathrooms and dressing rooms.', NULL, 'images/orders/mirror.png', 'orders', 'mirror', 'silver', '#C0C0C0', 'فضي', 'Silver', 'decor', 25, TRUE),
  ('حامل نباتات - أسود', 'Iron Plant Stand - Black', 'حامل نباتات حديدي بلون أسود، تصميم أنيق بطوابق متعددة لعرض الأزهار والنباتات. زخارف فنية على الجوانب تضفي جمالاً إضافياً. مثالي للحدائق والشرفات.', 'Black iron plant stand with an elegant multi-tier design for displaying flowers and plants. Artistic side decorations add extra beauty. Ideal for gardens and balconies.', NULL, 'images/orders/plant-stand.png', 'orders', 'plant-stand', 'black', '#1a1a1a', 'أسود', 'Black', 'outdoor', 24, TRUE),
  ('حامل نباتات - أخضر', 'Iron Plant Stand - Green', 'حامل نباتات حديدي بلون أخضر طبيعي، تصميم بطوابق متعددة. اللون الأخضر يندمج مع النباتات ويمنح المكان طبيعة خصبة. مثالي للحدائق والمشاتل.', 'Natural green iron plant stand with a multi-tier design. The green color blends with plants and gives the space a lush natural feel. Ideal for gardens and nurseries.', NULL, 'images/orders/plant-stand.png', 'orders', 'plant-stand', 'green', '#2E8B57', 'أخضر', 'Green', 'outdoor', 23, TRUE),
  ('حامل نباتات - أبيض', 'Iron Plant Stand - White', 'حامل نباتات حديدي بلون أبيض، تصميم أنيق بطوابق متعددة. اللون الأبيض يبرز جمال النباتات والأزهار. مثالي للشرفات وغرف المعيشة.', 'White iron plant stand with an elegant multi-tier design. The white color highlights the beauty of plants and flowers. Ideal for balconies and living rooms.', NULL, 'images/orders/plant-stand.png', 'orders', 'plant-stand', 'white', '#f0f0f0', 'أبيض', 'White', 'outdoor', 22, TRUE),
  ('درابزين حديد - أسود', 'Iron Railing - Black', 'درابزين حديد بلون أسود كلاسيكي، مزخرف بلفائف فنية وأشكال هندسية. تصميم متين وآمن يناسب الدرج والشرفات. مثالي للمنازل والمباني الكلاسيكية.', 'Classic black wrought iron railing with artistic scrollwork and geometric shapes. A sturdy and safe design suitable for stairs and balconies. Ideal for classic homes and buildings.', NULL, 'images/orders/railing.png', 'orders', 'railing', 'black', '#1a1a1a', 'أسود', 'Black', 'outdoor', 21, TRUE),
  ('درابزين حديد - ذهبي', 'Iron Railing - Gold', 'درابزين حديد بلون ذهبي فاخر، مزخرف بلفائف ملكية ولمسات ذهبية. يضفي طابعاً فخماً على الدرج والشرفات. مناسب للقاعات والفيلات الفاخرة.', 'Luxurious gold wrought iron railing with royal scrollwork and gold accents. Adds a luxurious touch to stairs and balconies. Suitable for luxury halls and villas.', NULL, 'images/orders/railing.png', 'orders', 'railing', 'gold', '#D4A017', 'ذهبي', 'Gold', 'outdoor', 20, TRUE),
  ('درابزين حديد - فضي', 'Iron Railing - Silver', 'درابزين حديد بلون فضي عصري، مزخرف بتصميم أنيق وبسيط. اللون الفضي يناسب الديكورات الحديثة والمعاصرة. مثالي للمباني والمكاتب العصرية.', 'Modern silver wrought iron railing with an elegant and simple design. The silver color suits modern and contemporary decors. Ideal for modern buildings and offices.', NULL, 'images/orders/railing.png', 'orders', 'railing', 'silver', '#C0C0C0', 'فضي', 'Silver', 'outdoor', 19, TRUE),
  ('درج حلزوني - أسود', 'Spiral Staircase - Black', 'درج حديد حلزوني بلون أسود أنيق، مصمم بعناية لتحمل الاستخدام المكثف. درابزين مزخرف بأشكال فنية مميزة. مناسب للمساحات الضيقة مع إمكانية تخصيص التصميم.', 'Elegant black wrought iron spiral staircase designed for heavy use. Ornate artistic railings. Suitable for tight spaces with customizable designs available.', NULL, 'images/orders/stairs-spiral.png', 'orders', 'stairs-spiral', 'black', '#1a1a1a', 'أسود', 'Black', 'stairs', 18, TRUE),
  ('درج حلزوني - ذهبي', 'Spiral Staircase - Gold', 'درج حديد حلزوني بلون ذهبي فاخر، درابزين مزخرف بلمسات ذهبية لامعة. تصميم فخم يضفي طابعاً ملكياً على المكان. مثالي للفيلات والقاعات الكبرى.', 'Luxurious gold wrought iron spiral staircase with shiny gold-accented railings. A grand design that adds a royal character to the space. Ideal for villas and grand halls.', NULL, 'images/orders/stairs-spiral.png', 'orders', 'stairs-spiral', 'gold', '#D4A017', 'ذهبي', 'Gold', 'stairs', 17, TRUE),
  ('درج حلزوني - فضي', 'Spiral Staircase - Silver', 'درج حديد حلزوني بلون فضي عصري، درابزين مزخرف بلمسات فضية أنيقة. اللون الفضي يمنح المكان مظهراً عصرياً وراقياً. مناسب للتصاميم الحديثة.', 'Modern silver wrought iron spiral staircase with elegant silver-accented railings. The silver color gives the space a contemporary and refined look. Suitable for modern designs.', NULL, 'images/orders/stairs-spiral.png', 'orders', 'stairs-spiral', 'silver', '#C0C0C0', 'فضي', 'Silver', 'stairs', 16, TRUE),
  ('درج مستقيم - أسود', 'Straight Staircase - Black', 'درج حديد مستقيم بلون أسود، مصنوع من الحديد المعالج حرارياً. درابزين مزخرف بتصميم كلاسيكي ودرجات واسعة مريحة. مناسب للاستخدام الداخلي والخارجي.', 'Straight black wrought iron staircase made from heat-treated iron. Classic-design ornate railings with wide comfortable steps. Suitable for indoor and outdoor use.', NULL, 'images/orders/stairs-straight.png', 'orders', 'stairs-straight', 'black', '#1a1a1a', 'أسود', 'Black', 'stairs', 15, TRUE),
  ('درج مستقيم - برونزي', 'Straight Staircase - Bronze', 'درج حديد مستقيم بلون برونزي، درابزين مزخرف بلمسات برونزية فاخرة. تصميم يجمع بين الأصالة والفخامة. مناسب للفلل والمنازل الكلاسيكية.', 'Bronze wrought iron straight staircase with luxurious bronze-accented railings. A design combining authenticity and luxury. Suitable for villas and classic homes.', NULL, 'images/orders/stairs-straight.png', 'orders', 'stairs-straight', 'bronze', '#CD7F32', 'برونزي', 'Bronze', 'stairs', 14, TRUE),
  ('درج مستقيم - رمادي', 'Straight Staircase - Grey', 'درج حديد مستقيم بلون رمادي عصري، تصميم أنيق مع درابزين بسيط. اللون الرمادي يناسب الديكورات المعاصرة والصناعية. مثالي للمباني الحديثة.', 'Modern grey wrought iron straight staircase with an elegant design and simple railings. The grey color suits contemporary and industrial decors. Ideal for modern buildings.', NULL, 'images/orders/stairs-straight.png', 'orders', 'stairs-straight', 'grey', '#808080', 'رمادي', 'Grey', 'stairs', 13, TRUE),
  ('طاولة قهوة حديد - أسود', 'Iron Coffee Table - Black', 'طاولة قهوة حديدية أنيقة بلون أسود، تصميم مضغوط بأرجل مزخرفة. مثالية لغرف المعيشة والاستقبال. حجم مناسب يتناسب مع مختلف المساحات.', 'Elegant black iron coffee table with decorated legs. Ideal for living rooms and reception areas. A suitable size that fits various spaces.', NULL, 'images/orders/table-coffee.png', 'orders', 'table-coffee', 'black', '#1a1a1a', 'أسود', 'Black', 'tables', 12, TRUE),
  ('طاولة قهوة حديد - نحاسي', 'Iron Coffee Table - Copper', 'طاولة قهوة حديدية بلون نحاسي دافئ، تصميم أنيق بأرجل مزخرفة. اللون النحاسي يضفي دفئاً وأناقة على غرفة المعيشة. قطعة ديكور مميزة وعملية.', 'Copper-toned iron coffee table with decorated legs. The copper color adds warmth and elegance to the living room. A distinctive and practical decor piece.', NULL, 'images/orders/table-coffee.png', 'orders', 'table-coffee', 'copper', '#B87333', 'نحاسي', 'Copper', 'tables', 11, TRUE),
  ('طاولة قهوة حديد - أبيض', 'Iron Coffee Table - White', 'طاولة قهوة حديدية بلون أبيض نقي، تصميم أنيق وبسيط. اللون الأبيض يمنح المكان إحساساً بالنظافة والراحة. مثالية للديكورات الفاتحة والعصرية.', 'Pure white iron coffee table with a simple, elegant design. The white color gives a sense of cleanliness and comfort. Ideal for light and contemporary decor.', NULL, 'images/orders/table-coffee.png', 'orders', 'table-coffee', 'white', '#f0f0f0', 'أبيض', 'White', 'tables', 10, TRUE),
  ('طاولة طعام حديد - أسود', 'Iron Dining Table - Black', 'طاولة طعام حديدية فاخرة بلون أسود، قاعدة مزخرفة بنقوش فنية أنيقة. تصميم متين يتحمل الاستخدام اليومي. مناسبة لغرف الطعام الكلاسيكية والعصرية على حد سواء.', 'Luxurious black iron dining table with an elegantly decorated base. A sturdy design built for daily use. Suitable for both classic and contemporary dining rooms.', NULL, 'images/orders/table-dining.png', 'orders', 'table-dining', 'black', '#1a1a1a', 'أسود', 'Black', 'tables', 9, TRUE),
  ('طاولة طعام حديد - ذهبي', 'Iron Dining Table - Gold', 'طاولة طعام حديدية بلون ذهبي فاخر، قاعدة مزخرفة بلمسات ذهبية لامعة. تضفي لمسة ملكية على غرفة الطعام. مثالية للمناسبات والضيافة الرسمية.', 'Gold luxury iron dining table with shining gold accents on the decorated base. Adds a royal touch to the dining room. Ideal for occasions and formal hospitality.', NULL, 'images/orders/table-dining.png', 'orders', 'table-dining', 'gold', '#D4A017', 'ذهبي', 'Gold', 'tables', 8, TRUE),
  ('طاولة طعام حديد - فضي', 'Iron Dining Table - Silver', 'طاولة طعام حديدية بلون فضي عصري، قاعدة مزخرفة بلمسات فضية راقية. اللون الفضي يمنح غرفة الطعام مظهراً عصرياً وأنيقاً. مناسبة للديكورات الحديثة.', 'Modern silver iron dining table with elegant silver accents on the decorated base. The silver color gives the dining room a modern and sophisticated look. Suitable for contemporary decor.', NULL, 'images/orders/table-dining.png', 'orders', 'table-dining', 'silver', '#C0C0C0', 'فضي', 'Silver', 'tables', 7, TRUE),
  ('دولاب حديد - أسود', 'Iron Wardrobe - Black', 'دولاب حديد متين بلون أسود أنيق، مصنوع من الحديد المجلفن المقاوم للصدأ. يتميز برفوف متعددة وأبواب محكمة الإغلاق. مثالي لتنظيم الملابس والمستلزمات.', 'Sturdy black iron wardrobe made from galvanized rust-resistant iron. Features multiple shelves and secure locking doors. Ideal for organizing clothes and supplies.', NULL, 'images/orders/wardrobe.png', 'orders', 'wardrobe', 'black', '#1a1a1a', 'أسود', 'Black', 'storage', 6, TRUE),
  ('دولاب حديد - برونزي', 'Iron Wardrobe - Bronze', 'دولاب حديد بلون برونزي فاخر، تصميم كلاسيكي مع زخارف فنية. اللون البرونزي يضفي طابعاً عتيقاً وراقياً على الغرفة. مناسب للديكورات الكلاسيكية والفاخرة.', 'Luxurious bronze iron wardrobe with a classic design and artistic details. The bronze color adds a vintage and refined touch to the room. Suitable for classic and luxury decor.', NULL, 'images/orders/wardrobe.png', 'orders', 'wardrobe', 'bronze', '#CD7F32', 'برونزي', 'Bronze', 'storage', 5, TRUE),
  ('دولاب حديد - رمادي', 'Iron Wardrobe - Grey', 'دولاب حديد بلون رمادي عصري، تصميم عملي وأنيق مع رفوف متعددة. اللون الرمادي يناسب مختلف الديكورات المعاصرة. هيكل صلب يتحمل الأوزان الثقيلة.', 'Modern grey iron wardrobe with a practical and elegant design with multiple shelves. The grey color suits various contemporary decors. Solid structure supporting heavy loads.', NULL, 'images/orders/wardrobe.png', 'orders', 'wardrobe', 'grey', '#808080', 'رمادي', 'Grey', 'storage', 4, TRUE),
  ('نافذة حديد - أسود', 'Iron Window - Black', 'نافذة حديد مزخرفة بلون أسود، نقوش يدوية فنية بأشكال هندسية وزهور. تصميم يجمع بين الأمن والجمال. مناسب للمنازل والمباني الكلاسيكية.', 'Ornate black wrought iron window with handcrafted geometric and floral patterns. A design combining security and beauty. Suitable for classic homes and buildings.', NULL, 'images/orders/window.png', 'orders', 'window', 'black', '#1a1a1a', 'أسود', 'Black', 'outdoor', 3, TRUE),
  ('نافذة حديد - برونزي', 'Iron Window - Bronze', 'نافذة حديد مزخرفة بلون برونزي، نقوش يدوية بلمسات نحاسية دافئة. اللون البرونزي يضفي طابعاً عتيقاً وأنيقاً. مناسبة للديكورات الكلاسيكية.', 'Ornate bronze wrought iron window with handcrafted warm copper-tone patterns. The bronze color adds a vintage and elegant touch. Suitable for classic decor.', NULL, 'images/orders/window.png', 'orders', 'window', 'bronze', '#CD7F32', 'برونزي', 'Bronze', 'outdoor', 2, TRUE),
  ('نافذة حديد - أبيض', 'Iron Window - White', 'نافذة حديد مزخرفة بلون أبيض، نقوش يدوية رقيقة وبسيطة. اللون الأبيض يمنح الواجهة مظهراً مشرقاً ونظيفاً. مناسبة للمنازل ذات الديكور الفاتح.', 'Ornate white wrought iron window with delicate and simple handcrafted patterns. The white color gives the facade a bright and clean appearance. Suitable for light-decor homes.', NULL, 'images/orders/window.png', 'orders', 'window', 'white', '#f0f0f0', 'أبيض', 'White', 'outdoor', 1, TRUE);

SELECT setval('products_id_seq', (SELECT COALESCE(MAX(id), 1) FROM products), TRUE);

COMMIT;

-- تم استيراد 66 منتج.
